# Generated by Django 4.2.11 on 2024-04-04 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='breed',
        ),
    ]
