# Generated by Django 4.2.11 on 2024-04-08 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_restaurant_friend_restaurants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='restaurants',
        ),
    ]
