# Generated by Django 4.2.11 on 2024-04-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_friend_restaurants'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='restaurants',
            field=models.ManyToManyField(to='main_app.restaurant'),
        ),
    ]
