# Generated by Django 5.0.4 on 2024-04-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_friend_restaurants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='activity name')),
                ('city', models.CharField(verbose_name='activity location(city)')),
            ],
        ),
    ]
