# Generated by Django 5.0.4 on 2024-04-11 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_activity'),
        ('main_app', '0006_friend_user'),
        ('main_app', '0006_hotel'),
    ]

    operations = [
    ]
