# Generated by Django 5.0.4 on 2024-04-11 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_merge_0006_activity_0006_friend_user_0006_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='friend',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.friend'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
